### ISSUE TITLE
Pandocomatic is confused by DOS line endings (from Talal)

### ISSUE THREAD

**Issue by htdebeer** [htdebeer/pandocomatic#34]
Pandocomatic seems to have trouble reading the metadata from a file with DOS line endings. And if it cannot mine the metadata, it does not know what to do.

**Comment by htdebeer** [comment]
Fixed by check-in "Enabled DOS line endings when mining for metadata in a file".

Changes will be in release 0.1.4.12

**Comment by talazem** [comment]
Thank you for the update, which I have now tested.

Unfortunately, I am still getting the following error:

/Library/Ruby/Gems/2.3.0/gems/psych-2.2.4/lib/psych.rb:377:in `parse': (<unknown>): found character that cannot start any token while scanning for the next token at line 6 column 1 (Psych::SyntaxError)
	from /Library/Ruby/Gems/2.3.0/gems/psych-2.2.4/lib/psych.rb:377:in `parse_stream'
	from /Library/Ruby/Gems/2.3.0/gems/psych-2.2.4/lib/psych.rb:325:in `parse'
	from /Library/Ruby/Gems/2.3.0/gems/psych-2.2.4/lib/psych.rb:252:in `load'
	from /Library/Ruby/Gems/2.3.0/gems/pandocomatic-0.1.4.12/lib/pandocomatic/pandoc_metadata.rb:68:in `load_file'
	from /Library/Ruby/Gems/2.3.0/gems/pandocomatic-0.1.4.12/lib/pandocomatic/command/convert_file_multiple_command.rb:50:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/pandocomatic-0.1.4.12/lib/pandocomatic/pandocomatic.rb:97:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/pandocomatic-0.1.4.12/lib/pandocomatic/pandocomatic.rb:97:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/pandocomatic-0.1.4.12/bin/pandocomatic:3:in `<top (required)>'
	from /usr/local/bin/pandocomatic:22:in `load'
	from /usr/local/bin/pandocomatic:22:in `<main>'

**Comment by htdebeer** [comment]
I get the same error if I run

    pandocomatic -c pandocomatic.yaml -i test.md

on your supplied test files.

However, if I adapt the test file to [fixed-test.txt](https://github.com/htdebeer/pandocomatic/files/1245139/fixed-test.txt) it works as expected. Note:

- pandoc and pandocomatic properties never start with a uppercase letter. So "Pandocomatic" should be "pandocomatic", "Pandoc" should be "pandoc", and "Output" should be "output".
- the pandoc property is an object rather than a list. So, use

    pandoc:
        output: myfile.docx

  rather than
    pandoc:
    - output: myfile.docx
- Finnally, in YAML, proper indentation is important. I think that some lines in the metadata have too much indentation. Reformatting seems to solve the issue, though.

**Comment by htdebeer** [comment]
I've created another fix related to this issue. A new version is available.
